language: go
os:
  - linux
go:
  - 1.11
services: mongodb
before_script:
  - "sudo apt-get install zookeeperd"
before_install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install:
  - go get github.com/Masterminds/glide
script:
  - go build $(glide nv)
  - go fmt $(glide nv)
  - go vet $(glide nv)
  - go test -i -race $(glide nv)
  - overalls -project=github.com/digota/digota -covermode=count -debug
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f86dea6fede293c375c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always